index:
    path: /
    controller: App\Controller\MainController::index
new:
    path: /new
    controller: App\Controller\NewProviderController::new
delete:
    path: /delete/{id}
    methods: GET
    controller: App\Controller\DeleteProviderController::delete
delete_form:
    path: /delete/{id}
    methods: POST
    controller: App\Controller\DeleteProviderController::delete_formHandler