index:
    path: /
    controller: App\Controller\MainController::index
new:
    path: /new
    controller: App\Controller\NewProviderController::new
delete:
    path: /delete/{id}
    methods: GET
    controller: App\Controller\DeleteProviderController::delete
edit:
    path: /edit/{id}
    controller: App\Controller\EditProviderController::edit